[tool.briefcase]
project_name = "God"
bundle = "com.example"
version = "0.2.0"
url = "https://example.com"
license = "MIT"
author = "You"
author_email = "you@example.com"

[tool.briefcase.app.god]
formal_name = "God"
description = "Local AI assistant (Flask + WebView + Tools + Updater)"
sources = ["app"]
requires = ["Flask==2.2.5", "requests==2.31.0"]
supported_platforms = ["iOS"]

[tool.briefcase.app.god.iOS]
icon = "app/static"
